# Generated by Django 5.1.4 on 2024-12-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='locality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='mass_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='rarity',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='size_x_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='size_y_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='size_z_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
